### HOME REQUEST
GET http://localhost:3000/home
Content-Type: application/json

### BYE REQUEST
GET http://localhost:3000/home
Content-Type: application/json

{
  "id": "bye"
}

### SECRET REQUEST
POST http://localhost:3000/secret_path
Content-Type: application/json

{
  "user": "jason",
  "pw": "thereisnone"
}